---
title: "Simulate BTS survey on scup"
date: "2024-01-05"
output: html_document
---

## Objective 
Simulate the BTS survey over the NEUS survey grid and the distributed scup population. 

Output: survey data containing numbers caught per tow/set, and length and age sampled data 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(SimSurvey)
suppressPackageStartupMessages(library(tidyverse))
library(data.table)
library(patchwork)
library(here)

# Load the population abundance and distribution 
pop <- readRDS(here("R", "scup", "data", "scup_dist.rds"))

set.seed(8675309)
```


## Simulate Survey
```{r}
surv_dat1 <- pop |>
  sim_survey(n_sims = 25,
             trawl_dim = c(2.7, 0.014),
             q = sim_logistic(k = 2, x0 = 2.5), #if plot = TRUE, xlim errors
             set_den = 0.001,
             min_sets = 3,
             #lengths_cap = # max # of lengths to collect per set
             #age_cap = 8, # max # of ages to sample per length group - all 8?
             age_sampling = "stratified", 
             #age_length_group = , # length group bin size (cm) - 
             age_space_group = "set", # spatial scale of stratified age sampling - ages taken each tow?
             resample_cells = TRUE)
```


```{r}
#q_fun <- sim_logistic(k = 2, x0 = 2.5)
```


```{r}
plot_survey(surv_dat1, which_year = 1, which_sim = 1)
plot_survey(surv_dat1, which_year = 2, which_sim = 1)
plot_survey(surv_dat1, which_year = 3, which_sim = 1)
```


```{r}
plot_survey(surv_dat1, which_year = 1, which_sim = 2)
plot_survey(surv_dat1, which_year = 2, which_sim = 2)
plot_survey(surv_dat1, which_year = 3, which_sim = 2)
```

```{r}
# check the number of sets allocated across the survey
strat_n <- surv_dat1$setdet |> filter(year == 1, sim == 1) |> group_by(strat) |> summarise(n_sets = length(set)) |> arrange(desc(n_sets))

sum(strat_n$n_sets)

```


```{r, include = FALSE}

saveRDS(surv_dat1, here("R", "scup", "data", "scup_survdat_25sims.rds"))
```

