---
title: "set density for NEFSC BTS survey"
author: "Catalina Roman"
date: "2023-05-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Load packages
#library(VAST)
#library(splines)
#library(effects)
#library(rio)
library(tidyverse)
#library(truncnorm)
#library(R.utils)
library(data.table)
library(here)
#library(mgcv)
library(patchwork)
library(sf)
```

```{r}
dat <- readRDS(here("data/rds/merged_data_complete.rds"))

dat <- dat |>
  mutate(code = str_c(STRATUM, CRUISE6, STATION)) 

(dat_n <- dat |>  
  group_by(SEASON,EST_YEAR) |>
  summarise(count = n_distinct(code)) |>
  pivot_wider(names_from = SEASON, values_from = count)
)


(dat_sum <- dat_n |>
  mutate(SUMA = rowSums((dat_n[,2:3]), na.rm = TRUE)) |>
  filter(!EST_YEAR %in% c(2017,2020))) #years removed due to lower number of tows that pull the mean down

mean(dat_sum$FALL)
mean(dat_sum$SPRING)
summary(dat_sum)

```

```{r}

# load and manipulate the bottom trawl survey strata shapefile
strata <- sf::st_read(here("gis", "NEFSC-BTS_strata_Jun2022.gdb"), layer = "NEFSC_BTS_ActiveStrata_Jun2022") #|>
  
strata <- strata |>
  mutate(Area_SqM = st_area(strata), 
         Area_SqKm = as.numeric(Area_SqM / 1000000)) |>
  rename(STRATUM=Strata_Num)
  # dplyr::select(STRATUM, Area_SqNm) |> # select variables to be used in calculations below
  # sf::st_set_geometry(NULL) |> # remove the coordinates; changes the sf to a df
  # unique() |> # identify unique stratum only 
  # mutate(RelWt = Area_SqNm / sum(Area_SqNm)) # calculate the relative weight of each stratum based on its proportion of the total survey footprint area; to be used in later calculations.

sum(strata$Area_SqKm)
mean(strata$Area_SqKm)
max(strata$Area_SqKm)
min(strata$Area_SqKm)

strata_n <- st_set_geometry(strata, NULL)
ggplot(strata_n) + geom_col(aes(x=as.factor(STRATUM), y=Area_SqKm)) + 
  theme(axis.text.x = element_text(angle = 90))

```
###Calculation of density 
```{r}
#density for Fall

mean(dat_sum$FALL)/sum(strata$Area_SqKm)

#density for Spring

mean(dat_sum$SPRING)/sum(strata$Area_SqKm)

##SET DENSITY = 0.005 for a year (both spring and fall)

```
```{r}
(strata_table <- strata_n |>
  group_by(STRATUM) |>
  arrange(desc(Area_SqKm)) 
)

head(strata_table,1)
tail(strata_table,1)
```

```{r}
## number of tows per year for the smallest stratum, by season

(dat_n1 <- dat |>  
  group_by(SEASON,EST_YEAR, STRATUM) |>
  summarise(count = n_distinct(code)) |>
  pivot_wider(names_from = SEASON, values_from = count) |>
     filter(!EST_YEAR %in% c(2017,2020)) |> #years removed due to lower number of tows that pull the mean down
    left_join(strata,by="STRATUM") |>
    dplyr::select(EST_YEAR, STRATUM,FALL,SPRING,Area_SqKm) |>
   pivot_longer(cols = c("FALL","SPRING"), names_to = "SEASON", values_to = "count")
)

ggplot(dat_n1) + geom_point(aes(x=Area_SqKm, y=count, shape=SEASON, color=SEASON)) + facet_wrap(~EST_YEAR) +
  labs(x = "Stratum area (Km^2)",y = "number of tows")

ggplot(dat_n1) + geom_point(aes(x=Area_SqKm, y=count, shape=SEASON, color=SEASON)) +
  labs(x = "Stratum area (Km^2)",y = "number of tows")



```
```{r}

(dat_n1b <- dat |>  
  group_by(SEASON,EST_YEAR, STRATUM) |>
  summarise(count = n_distinct(code)) |>
  pivot_wider(names_from = SEASON, values_from = count) |>
     filter(!EST_YEAR %in% c(2017,2020)) |> #years removed due to lower number of tows that pull the mean down
    left_join(strata,by="STRATUM") |>
    dplyr::select(STRATUM,FALL,SPRING,Area_SqKm) |>
   pivot_longer(cols = c("FALL","SPRING"), names_to = "SEASON", values_to = "count")
)

```


```{r}
##average the number of tows per season per stratum 

(dat_n2 <- dat |>
  group_by(SEASON, EST_YEAR, STRATUM) |>
  summarise(count = n_distinct(code), .groups = "drop") |>
  filter(!EST_YEAR %in% c(2017,2020)) |> #years removed due to lower number of tows that pull the mean down
  group_by(SEASON, STRATUM) |>
  summarise(mean = round(mean(count), digit = 0))  |>
  pivot_wider(names_from = SEASON, values_from = mean) |>
    left_join(strata,by="STRATUM") |>
    dplyr::select(STRATUM,FALL,SPRING,Area_SqKm)
)

sum(dat_n2$Area_SqKm)
ggplot(dat_n2) + geom_point(aes(x=Area_SqKm, y=den_FALL)) 

mean(dat_n2$den_FALL)
range(dat_n2$den_FALL)

mean(dat_n2$den_SPRING)
range(dat_n2$den_SPRING)

max(dat_n2$FALL)
max(dat_n2$SPRING)

  
```

###Validation of density calculation

```{r}
#mean tows per season
mean(dat_sum$FALL)
mean(dat_sum$SPRING)

(density_fall <- mean(dat_sum$FALL)/sum(strata$Area_SqKm))
(density_spr <-mean(dat_sum$SPRING)/sum(strata$Area_SqKm))

den <- 0.001

#sim set function calculates the number of sets by set_den * strata

(dat_n3 <- dat_n2 |>
  mutate(tows_val = round(den*Area_SqKm))
)

```
