---
title: "Simulate scup abundance"
author: "Catalina Roman"
date: "2023-11-25"
output: html_document
---

## Objective ####
Script will simulate summer flounder population and abundances based on stock assessment data

Output: Initial numbers at age, numbers at length, total mortality at age for a set number of years and ages, and recruitment for a given number of years 

```{r setup, include=FALSE}
library(learnr)
library(SimSurvey)
library(dplyr)
library(forcats)
library(sdmTMB)
library(plotly)
library(here)
library(raster)
library(stars)
suppressPackageStartupMessages(library(tidyverse))
library(data.table)
library(patchwork)
library(oce)


knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, 
                      out.width = "100%", out.height = "450px")

```

_Stock Assessment Data_

```{r stock data}
set.seed(8675309)

##remember to convert to millions
#MTA
# Rec_age0 <- c(145686, 133452, 92479, 69155, 129722, 74488, 112867, 99376, 39627, 39796, 72976, 42726, 37025, 93345,106668, 223962, 147688, 141201, 89909, 91455, 138744, 218815, 255024, 257622, 227491, 129655, 149488, 216850, 124572, 122412, 282838, 415041, 142853, 84306, 100436, 34113) 

#Rec_age0_5 <- c(415041, 142853, 84306, 100436, 34113)

#Benchmark SA 
Rec_age0 <- c(132,127,82,63,118,67,100,89,36,37,61,35,29,78,97,222,146,138,84,84,127,197,222,218,185,98,107,142,75,61,112)*1e6 
  
Rec_age0_5 <- c(107,142,75,61,112)*1e6

Rec.all<-mean(Rec_age0)
Rec<-mean(Rec_age0_5)
#sd(Rec_age0)
#sd(Rec_age0_5)


# Z <- c(1.054, 1.276, 1.233, 1.266, 1.269, 1.229, 1.044, 1.619, 1.669, 1.561, 1.855, 1.467, 1.269, 
#        0.951, 0.657, 0.501, 0.459, 0.333, 0.294, 0.337, 0.312, 0.269, 0.288, 0.287, 0.252, 0.258, 
#        0.276, 0.279, 0.278, 0.315, 0.305, 0.34, 0.314, 0.326, 0.311, 0.336)
# 
# Z_5 <- c(0.34, 0.314, 0.326, 0.311, 0.336) 
# mean(Z_5)
# sd(Z_5)
# log(sd(Z_5))

F_age<-c(0.009,	0.039,	0.09,	0.127,	0.122,	0.119,	0.072,	0.023)
M <- 0.2
Z_age<- F_age + M
```


## Simulate Abundance 
```{r sim abundance}

set.seed(5134235)


pop <- sim_abundance(ages = 0:7, years = 1:4, 
                     R = sim_R(log_mean = log(Rec), log_sd = 0.001, plot = TRUE),  
                     Z = sim_Z(log_mean = log(Z_age), log_sd = 0.001, plot = TRUE),
                     growth = sim_vonB(Linf = 46.6, K = 0.15, plot = TRUE)) 

#Z_fun <- sim_Z(log_mean = log(0.5), log_sd = 0.1, phi_age = 0.9, phi_year = 0.9, plot = TRUE)
#Z_fun(years = 1:100, ages = 1:20)

round(pop$N)
plot_surface(pop, mat = "N")
Nage <- tibble(age = 0:7, pop$N0)


```


```{r, include = FALSE}
### save the data
saveRDS(pop, here::here("R", "scup", "data", "scup_abundance.rds"))
saveRDS(Nage, here::here("R", "scup", "data", "scup_Nage.rds"))
```

