---
title: "Reallocated tows Fall"
author: "Catalina Roman"
date: "2024-01-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read pop abundance, distribution and survey
```{r}
set.seed(8675309)

pop <- readRDS(here("R", "scup", "data", "scup_dist_spr.rds"))
surv_dat1 <- readRDS(here("R", "scup", "data", "scup_survdat_25sims_spr.rds"))

```

```{r}
# grid_xy <- readRDS(here("data", "survey_grid_062022.rds")) |>
#   rename(strat = STRATUM, 
#          x = X, 
#          y = Y) |>
#   mutate(division = 1) |>
#   dplyr::select(x, y, cell, division, strat, depth, AREA_CODE) |>
#   data.table::as.data.table()
# 
# grid_xy <- readRDS(here("data", "rds", "survey_grid_062022.rds")) |>
#   rename(strat = STRATUM, 
#          x = X, 
#          y = Y) |>#, # rename to match column calls within SimSurvey functions
#          #depth = AVGDEPTH) |>
#   mutate(division = 1) |>#, # add division information
#          #x = X/1000, # convert to km
#          #y = Y/1000) |>
#   dplyr::select(x, y, cell, division, strat, depth, AREA_CODE) |>
#   data.table::as.data.table()
# 
#grid_stars <- readRDS(here("data",  "survey_grid_stars_012023.rds"))
#grid_ras <- rasterFromXYZ(grid_xy, crs = 32618)
#grid_stck <- stack(grid_ras)
```


```{r}
wind_tows <- surv_dat1$setdet |>
  filter(AREA_CODE == 1) #tows occuring inside wind areas | AREA CODE = 1
wind_tows
```

```{r}
wind_cells <- wind_tows |>
  group_by(sim,year,strat) |>
  distinct(cell) 

```

```{r}
wind_strat <- unique(wind_cells$strat)
```

locate cells outside the grid
```{r}

out_wa_grid <- pop$grid_xy |>
  filter(strat %in% wind_strat, AREA_CODE == 2) |> 
  group_by(strat)|>
  nest() 
```

out_wa_grid does not contain info for certain strata 
```{r}
wind_summ <-  wind_tows |>
   #filter(strat != 3200) |> 
   group_by(sim, year, strat ) |>
   nest() |>
   mutate(count = map(data,~length(.$set))) |>
  rename(wind_tows = data)
```

```{r}
join_data <- wind_summ |>
  left_join(out_wa_grid, by="strat") 

out_strat <- unique(out_wa_grid$strat) 
```
remove nulls
```{r}
join_data2 <- join_data |>
  filter(strat %in% out_strat) 

join_data_nulls <- anti_join(join_data, join_data2, by=c("sim", "strat", "year"))
   

```


```{r}
new_locations <- join_data2 |>
  mutate(new = map2(data, count, ~ slice_sample(.x, n=.y, replace=TRUE)),
         tow_info = map(wind_tows, ~select(., !c(x,y,cell,depth, division, AREA_CODE, n, n_aged, n_measured, N))),
         new_set_loc = map2(new, tow_info, ~bind_cols(.x, .y))) |>
  select(c(sim, year, strat, new_set_loc)) |>
  unnest(cols=new_set_loc) |>
  #select(!(division)) |>
  relocate(set, .after = last_col())

```

New survey only with rellocated tows to generate setden for those tows
```{r}

surv_reallocation <- pop |>
  sim_survey(n_sims = 25,
             trawl_dim = c(2.7, 0.014),
             q = sim_logistic(k = 2, x0 = 2.5), #if plot = TRUE, xlim errors
             set_den = 0.001,
             min_sets = 3,
             #lengths_cap = # max # of lengths to collect per set
             #age_cap = 8, # max # of ages to sample per length group - all 8?
             age_sampling = "stratified", 
             #age_length_group = , # length group bin size (cm) - 
             age_space_group = "set", # spatial scale of stratified age sampling - ages taken each tow?
             custom_sets = new_locations,
             resample_cells = TRUE)
```



```{r, include = FALSE}
saveRDS(new_locations, here("R", "scup", "data", "new_locations_spr.rds"))
saveRDS(surv_reallocation, here("R", "scup", "data", "scup_survreallocation_25sims_spr.rds"))
```
